version: '3'
services:
  dashboard:
    build: .
    depends_on: 
      - mongo
    volumes: 
      - /node_modules
      - .:/app
    env_file: 
      - .env
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
